# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  header:
    - '&#676C6D&l&m               &r&#676C6D&l( &#193df8&lW&#0053ff&le&#0064ff&ll&#0073ff&lc&#0080ff&lo&#008cff&lm&#0097ff&le
  &#00a2ff&lt&#00acff&lo &#00b6ff&lO&#00bfff&lr&#00c8fd&lb&#00d0f8&li&#0dd8f4&ls &f&lTowny
  &#676C6D&l)&#676C6D&l&m              '
    - ''
    - '&f%server_online%&#1788E7/&f%server_max_players% &#09A1CEPlayers Connected &#676C6D&l'
    - '&#09A1CEVote Party: &f%denizen_<server.flag[votes].mod[100].sub[100].abs>%&#1788E7/&f100'
  footer:
    - ''
    - '&f&lWebsite&r&#0087ff ┃ &#00a9ffo&#00b1ffr&#00b9ffb&#00c1ffi&#00c8ffs&#00cffbmc&#00d6f6.&#00dcf2c&#00e3edo&#00e9eam '
    - '&F&lStore&#0087ff ┃ &#008fffs&#0096fft&#009dffo&#00a4ffr&#00abffe&#00b1ff.&#00b8ffo&#00beffr&#00c4ffb&#00cafei&#00cffas&#00d5f7m&#00daf3c&#00e0ef.&#00e5ecc&#00eae9o&#0fefe6m'
    - '&#676C6D&l┃┃ &#193df8&op&#0050ff&ol&#005fff&oa&#006dff&oy&#0079ff&o.&#0084ff&oo&#008eff&or&#0098ff&ob&#00a1ff&oi&#00aaff&os&#00b2ff&om&#00bbff&oc&#00c2ff&o.&#00cafc&oc&#00d1f8&oo&#0dd8f4&om
  &#676C6D&l┃┃'
    - ''
    - '&#676C6D&l&m'
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2;world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld

scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
    - "PLACEHOLDER_A_TO_Z: %townyadvanced_towny_tag_override%"
  case-sensitive-sorting: true
  disable-in-worlds:
    - disabledworld
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: 0.30
    disable-in-worlds:
      - disabledworld
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

yellow-number-in-tablist:
  enabled: false
  value: "%ping%"
  disable-in-worlds:
    - disabledworld

belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld

prevent-spectator-effect:
  enabled: false

bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

per-world-playerlist:
  enabled: false
  # players with tab.staff will always see all players
  allow-bypass-permission: false
  # players in these worlds will always see all players
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 5
  respect-other-plugins: true
  disable-in-worlds:
    - disabledworld
  scoreboards:
    scoreboard1:
      title: "%animation:ServerName%"
      lines:
      - '  &#0084ff&l&m &#0088ff&l&m &#008cff&l&m &#008fff&l&m &#0093fe&l&m &#0096fa&l&m &#0099f7&l&m &#009df3&l&m &#00a0ef&l&m &#00a3eb&l&m &#00a6e7&l&m &#00a9e4&l&m &#00abe0&l&m &#00aedd&l&m &#00b1d9&l&m &#00b3d6&l&m &#2db5d3&l&m &#47b8d0&l&m &#59bace&l&m     &r     '
      - '&7'
      - '  &#59bace&l• &f%server_online% &#009df3online '
      - '  &#59bace&l• &#009df3Ping: &f%player_ping%&fms '
      - '&7'  
      - '  &#59bace&l• &#009df3Nation - &f&l%denizen_<player.nation.name.if_null[NONE]>%'
      - '  &#59bace&l• &#009df3Town - &F&l%denizen_<player.town.name.if_null[NONE]>%'
      - '&7'
      - '  &#59bace&l• &#009df3Balance: &f&l%denizen_<player.formatted_money>%'
      - '  &#59bace&l• &#009df3Party: &f%denizen_<server.flag[votes].mod[100].sub[100].abs>% &#009df3votes left'
      - '&7'
      - '  &#0084ff&l&m &#0088ff&l&m &#008cff&l&m &#008fff&l&m &#0093fe&l&m &#0096fa&l&m &#0099f7&l&m &#009df3&l&m &#00a0ef&l&m &#00a3eb&l&m &#00a6e7&l&m &#00a9e4&l&m &#00abe0&l&m &#00aedd&l&m &#00b1d9&l&m &#00b3d6&l&m &#2db5d3&l&m &#47b8d0&l&m &#59bace&l&m     &r     '    
      - '&7'
      - '     %animation:web%'
      - '&#B4B4B4&o Disable with /sb'

ping-spoof:
  enabled: false
  value: 0

fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"

placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  "%afk%":
    true: " &o[AFK]&r"
    false: ""
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" #placeholder did not parse correctly, show real name instead

conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 300
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
    "%server_unique_joins%": 5000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_townyadvanced_color%": 600

#if none of the above fits your needs, you can enable this to give groups using tab.group.<group name from the list below> permission
assign-groups-by-permissions: false

#if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
