BCauldron:
  8aecda1a-b7c7-4d16-85a0-fba48eb8fc39: {}
  6d0794cc-9cae-4ac2-8e1d-22fa5069e817: {}
  1ca15323-7dc7-419e-a7e7-db214851b44f: {}
  3dc85d91-3cc8-4b27-9753-a2b3a33510ce: {}
  204a4a4f-c419-4d4c-bfe8-b35548da505e: {}
  7ce438e0-527b-49dc-8c16-293c0c455278: {}
  63966306-a917-468a-a4db-57600d4370a7: {}
  268d4220-83fc-4576-a9f5-0a3e955c9535: {}
  82500574-c35d-4b6b-9716-eeda35fdcd7d: {}
  ada45c4e-2486-4027-a16f-3baca4c9202e: {}
  dd291063-b18c-4973-b5d8-580c3d32dfcb: {}
  933bff0e-3f9f-470f-a998-ec29cbd439b6: {}
  ffa57e35-f50e-40f0-bcd2-9782a289651a: {}
  6bef5edf-23c1-45d9-a8e9-704561ea48a9: {}
  973636e1-02be-4dcf-b053-55966c36bfa4: {}
  0742b3f3-d5c7-4548-8bd6-6b457d2fad9c: {}
  f134f1b9-737a-4a9b-8986-bce4869ebde1: {}
  0f6011b0-90e2-41fd-bdaf-af324b9fba61: {}
  091fe923-8dcb-42f4-bafe-c9e271ca0bce: {}
Barrel:
  8aecda1a-b7c7-4d16-85a0-fba48eb8fc39:
    '0':
      spigot: 2085/63/-7419
      bounds: 2086,63,-7420,2087,64,-7419
    '1':
      spigot: 10933/107/-6047
      sign: 2
      bounds: 10929,107,-6048,10932,109,-6046
    '2':
      spigot: 34056/64/-11259
      sign: 2
      bounds: 34057,64,-11260,34060,66,-11258
    '3':
      spigot: 34062/63/-11279
      bounds: 34063,63,-11280,34064,64,-11279
    '4':
      spigot: 34044/64/-11263
      sign: 2
      bounds: 34045,64,-11264,34048,66,-11262
    '5':
      spigot: 34054/64/-11263
      sign: 2
      bounds: 34050,64,-11264,34053,66,-11262
    '6':
      spigot: 34062/63/-11270
      bounds: 34063,63,-11271,34064,64,-11270
    '7':
      spigot: 34062/63/-11267
      bounds: 34063,63,-11268,34064,64,-11267
    '8':
      spigot: 34062/63/-11276
      bounds: 34063,63,-11277,34064,64,-11276
    '9':
      spigot: 34058/63/-11278
      bounds: 34059,63,-11279,34060,64,-11278
    '10':
      spigot: 34058/63/-11267
      bounds: 34059,63,-11268,34060,64,-11267
    '11':
      spigot: 34054/64/-11259
      sign: 2
      bounds: 34050,64,-11260,34053,66,-11258
    '12':
      spigot: 2064/63/-7416
      bounds: 2064,63,-7415,2065,64,-7414
    '13':
      spigot: 4244/51/-8042
      bounds: 4244,51,-8041,4245,52,-8040
      time: 83.30048
      inv:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 2730
          type: POTION
          meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Whiskey"}],"text":""}'
            lore:
            - '{"extra":[{"text":"§t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Single
              Malt"}],"text":""}'
            - '{"extra":[{"text":"§u"}],"text":""}'
            - '{"extra":[{"text":"§s"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"⭑⭑⭑"}],"text":""}'
            - '{"extra":[{"text":"§v"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Ingredients"}],"text":""}'
            - '{"extra":[{"text":"§w"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"10
              minutes fermented"}],"text":""}'
            - '{"extra":[{"text":"§p"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"2-times
              Distilled"}],"text":""}'
            - '{"extra":[{"text":"§y"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"16
              Years Barrel aged"}],"text":""}'
            - '{"extra":[{"text":"§z"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Woodtype"}],"text":""}'
            ItemFlags:
            - HIDE_POTION_EFFECTS
            PublicBukkitValues:
              brewery:brewdata: '[B;86B,1B,0B,0B,6B,79B,0B,20B,2B,65B,-127B,-103B,-103B,64B,-64B,0B,0B,0B,7B,87B,104B,105B,115B,107B,101B,121B,0B,0B,0B,10B,1B,0B,2B,83B,73B,0B,5B,87B,72B,69B,65B,84B,0B,0B,0B,10B]'
            custom-color:
              ==: Color
              RED: 255
              BLUE: 0
              GREEN: 165
        '1':
          ==: org.bukkit.inventory.ItemStack
          v: 2730
          type: POTION
          meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Whiskey"}],"text":""}'
            lore:
            - '{"extra":[{"text":"§t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Single
              Malt"}],"text":""}'
            - '{"extra":[{"text":"§u"}],"text":""}'
            - '{"extra":[{"text":"§s"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"⭑⭑⭑"}],"text":""}'
            - '{"extra":[{"text":"§v"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Ingredients"}],"text":""}'
            - '{"extra":[{"text":"§w"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"10
              minutes fermented"}],"text":""}'
            - '{"extra":[{"text":"§p"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"2-times
              Distilled"}],"text":""}'
            - '{"extra":[{"text":"§y"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"16
              Years Barrel aged"}],"text":""}'
            - '{"extra":[{"text":"§z"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"Woodtype"}],"text":""}'
            ItemFlags:
            - HIDE_POTION_EFFECTS
            PublicBukkitValues:
              brewery:brewdata: '[B;86B,1B,0B,0B,6B,79B,0B,20B,2B,65B,-127B,-103B,-103B,64B,-64B,0B,0B,0B,7B,87B,104B,105B,115B,107B,101B,121B,0B,0B,0B,10B,1B,0B,2B,83B,73B,0B,5B,87B,72B,69B,65B,84B,0B,0B,0B,10B]'
            custom-color:
              ==: Color
              RED: 255
              BLUE: 0
              GREEN: 165
    '14':
      spigot: 10937/107/-6041
      sign: 2
      bounds: 10938,107,-6042,10941,109,-6040
    '15':
      spigot: 27932/58/6959
      bounds: 27932,58,6960,27933,59,6961
    '16':
      spigot: 34062/63/-11273
      bounds: 34063,63,-11274,34064,64,-11273
    '17':
      spigot: 4238/51/-8042
      bounds: 4238,51,-8041,4239,52,-8040
      time: 90.45092
      inv:
        '0':
          ==: org.bukkit.inventory.ItemStack
          v: 2730
          type: POTION
          meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Spicy
              Rum"}],"text":""}'
            lore:
            - '{"extra":[{"text":"§t"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"Spiced
              by the barrel"}],"text":""}'
            - '{"extra":[{"text":"§u"}],"text":""}'
            - '{"extra":[{"text":"§s"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"⭑⭑⭑"}],"text":""}'
            - '{"extra":[{"text":"§v"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Ingredients"}],"text":""}'
            - '{"extra":[{"text":"§w"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"5
              minutes fermented"}],"text":""}'
            - '{"extra":[{"text":"§p"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"2-times
              Distilled"}],"text":""}'
            - '{"extra":[{"text":"§y"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_red","text":"34
              Years Barrel aged"}],"text":""}'
            - '{"extra":[{"text":"§z"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Woodtype"}],"text":""}'
            ItemFlags:
            - HIDE_POTION_EFFECTS
            PublicBukkitValues:
              brewery:brewdata: '[B;86B,1B,0B,0B,6B,79B,0B,24B,2B,66B,8B,51B,21B,64B,0B,0B,0B,0B,9B,83B,112B,105B,99B,121B,32B,82B,117B,109B,0B,0B,0B,5B,1B,0B,2B,83B,73B,0B,10B,83B,85B,71B,65B,82B,95B,67B,65B,78B,69B,0B,0B,0B,14B]'
            custom-color:
              ==: Color
              RED: 128
              BLUE: 0
              GREEN: 0
    '18':
      spigot: 4240/51/-8042
      bounds: 4240,51,-8041,4241,52,-8040
    '19':
      spigot: 4242/51/-8042
      bounds: 4242,51,-8041,4243,52,-8040
  6d0794cc-9cae-4ac2-8e1d-22fa5069e817: {}
  1ca15323-7dc7-419e-a7e7-db214851b44f: {}
Worlds:
  8aecda1a-b7c7-4d16-85a0-fba48eb8fc39: world
  0414571a-4a42-4276-b6aa-ec1581426563: world_nether
  81dd040c-4aa7-4408-ba3e-2170ddd5b884: world_the_end
  f02ddf83-a728-43c7-8cfa-0360a107b241: world_nether
  146fcf4c-96ca-443b-bc15-6ece4b3acf5c: world_the_end
  cb513a1c-2acf-420f-9cf2-fd504a2db2ff: world_nullscape_end_island
  160da198-cf39-48be-9d7c-f5664afd8d64: world_the_end
  281849fc-5849-4b75-94b6-a1f945495818: world_luminous_luminous_end
  1d7b6a68-4320-4722-9a36-7d936caa45cd: world_luminous_the_deadlands
  fe37f540-1ac5-4517-9e62-a282effec887: world_nether
  cbe2678f-aeba-4e8e-87c3-dda53684a59e: world_the_end
  46b7b1f6-aa93-4697-9391-a53002c9de70: world_nether
  27541c94-efa4-40d8-9dc5-270d36e1ba0e: world_the_end
  aa8e6257-4db5-4c26-91f8-431ee6a2815e: world_luminous_luminous_end
  b5cf9f97-c861-4708-9f7d-fb51ab951dd5: world_luminous_the_deadlands
  9ef28c2a-897f-4968-8f68-da0a6a0665fd: world_nether
  4ca37d8f-cf46-4d0e-a874-3a7b17c97787: world_nether
  665febb7-2ddf-46b9-96fe-4aa0e56af31e: world_nether
  123c1bc7-efb3-4132-a471-4a6c485369ea: world_nether
  e026fa78-c1ac-4157-a5df-519a6dece16b: world_nether
  8e59b213-86c6-4973-adf7-ac4bcda74654: world_the_end
  006963a7-b42f-4053-9ab7-d62d99b62686: world_nether
  e1a4a6d9-5312-48cd-ae4a-ac1ead6b4b3f: world_the_end
  f00ee626-53fc-4bfc-8204-059c6f41d8f5: test
  b74cdea5-4c44-402f-8c99-c93fa3dab83c: world_nether
  e4ef47aa-59c9-4f3a-a878-33161f81da9a: world_the_end
  7c4cbf7d-b2e8-442b-ae33-7f70467c5a06: world
  6d0794cc-9cae-4ac2-8e1d-22fa5069e817: world_nether
  1ca15323-7dc7-419e-a7e7-db214851b44f: world_the_end
  1308ca8c-9e63-42d8-b518-b7db9554fd6a: world_minecraft_actual_nether
  9b410bd8-8981-4fcb-8a55-68949a16e0b2: world_luminous_luminous_end
  19d55ef2-88d2-4f21-b881-248e252c2482: world_luminous_the_deadlands
  a026bbd4-1273-4c3b-a276-86efa4838b00: world_minecraft_actual_nether
  1ddd5bcd-f93b-4ac8-bb21-f729d024d893: better_nether
  091fe923-8dcb-42f4-bafe-c9e271ca0bce: nether
  0f6011b0-90e2-41fd-bdaf-af324b9fba61: nether
  f134f1b9-737a-4a9b-8986-bce4869ebde1: nether
  0742b3f3-d5c7-4548-8bd6-6b457d2fad9c: nether
  973636e1-02be-4dcf-b053-55966c36bfa4: nether
  6bef5edf-23c1-45d9-a8e9-704561ea48a9: nether
  ffa57e35-f50e-40f0-bcd2-9782a289651a: nether
  933bff0e-3f9f-470f-a998-ec29cbd439b6: nether
  dd291063-b18c-4973-b5d8-580c3d32dfcb: nether
  ada45c4e-2486-4027-a16f-3baca4c9202e: nether
  82500574-c35d-4b6b-9716-eeda35fdcd7d: nether
  268d4220-83fc-4576-a9f5-0a3e955c9535: nether
  63966306-a917-468a-a4db-57600d4370a7: nether
  7ce438e0-527b-49dc-8c16-293c0c455278: nether
  204a4a4f-c419-4d4c-bfe8-b35548da505e: nether
  3dc85d91-3cc8-4b27-9753-a2b3a33510ce: nether
