itemName: '&eBaby Mask'
lore:
  - '&7A mask!'

potionType:
  - WEAKNESS;2
  - SPEED;5

on-wear-commands:
  - 'give %player% diamond 1'

on-remove-commands:
  - 'give %player% diamond 2'

timed-commands:
  10:
    - 'example command %player%'
    - 'example command2 %player%'
  15:
    - 'example command3 %player%'

periodic-commands:
  10:
    - 'give %player% emerald 1'
  20:
    - 'give %player% obsidian 2'

keep-on-death: true
hide-nametag: true
fly: true

add-permission: 'example.permission'

chat-format: '&e[Baby] &d%player%: &a%message%'

custom-join-message: '&a&n%player%&d joined wearing %mask%.'

effects-on-pvp:
  - 'INCREASE_DAMAGE;3;5'

damage-modifiers:
  extra-damage: 5.0
  damage-reduction: 10.0

mask-disguise:
  entity-type: CREEPER
  custom-name: '&a&lCreeper'

enchantments:
  DAMAGE_ALL: 1
  DURABILITY: 2

item-flags:
  - HIDE_ATTRIBUTES

gun-modifiers:
  bazooka:
    extra-damage: 30.0
    damage-reduction: 20.0
  grenade:
    extra-damage: 30.0
    damage-reduction: 20.0

custom-effects:
  AUTO_SMELT:
    particle-enabled: true
  MONEY_MULTIPLIER:
    multiplier: 2.0
    message-enabled: true
    message: '&aYour mask multiplier actually gave you&e $%money%&a!'
  NO_FALL_DAMAGE:
    message-enabled: true
    message: '&aAh.. what an easy landing!'
  SATURATION:
    message-enabled: true
    message: '&6Wow.. I suddenly got fed!'
  EXP_MULTIPLIER:
    multiplier: 2.0
    message-enabled: true
    message: '&aYour exp multiplier actually gave you &d%exp% &aexp!'
  EXTRA_HEALTH:
    max-health: 40.0

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NzI2NTU4NjQ2ODcsInByb2ZpbGVJZCI6IjIzZjFhNTlmNDY5YjQzZGRiZGI1MzdiZmVjMTA0NzFmIiwicHJvZmlsZU5hbWUiOiIyODA3Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83MjY5OTEwMTkzMGM4OWY2YzcxMmNjYjBjNjI4MDhhMzk5NzUyMDcxMDUwMzlmZTU4NzY2ZjJjODc2OGYyZDkxIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NzI2NTU4ODMxMTksInByb2ZpbGVJZCI6ImIwZDczMmZlMDBmNzQwN2U5ZTdmNzQ2MzAxY2Q5OGNhIiwicHJvZmlsZU5hbWUiOiJPUHBscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmM4YmQzZjAwYThmZTA5YmI1ZTEyODUyYWIyZGU5NjM2ZjI4Yzg5MjI3MGEyODNhYzQyZmRlMzViZmIyZjJmNiJ9fX0=;eyJ0aW1lc3RhbXAiOjE1NzI2NTU4OTg5MzMsInByb2ZpbGVJZCI6IjE5MjUyMWI0ZWZkYjQyNWM4OTMxZjAyYTg0OTZlMTFiIiwicHJvZmlsZU5hbWUiOiJTZXJpYWxpemFibGUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNiZGNkYzA5MTY0MThjZjgyZGNjNmQxYjkxNmNmZTgzZTU1ZTc0NzFlODA5NTMwZDNiYWM0NDZmMjk3N2UyYmQifX19;eyJ0aW1lc3RhbXAiOjE1NzI2NTU5MjY2MjEsInByb2ZpbGVJZCI6IjgyYzYwNmM1YzY1MjRiNzk4YjkxYTEyZDNhNjE2OTc3IiwicHJvZmlsZU5hbWUiOiJOb3ROb3RvcmlvdXNOZW1vIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTIwYTkwNmMzNzRkYmMyZWM0NTIzYzkwYTVjNGUwNjA0ZDA5YmZkZTlhN2VkYWQxMWE5M2NkMDhkZDk3YmFkIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NzI2NTU4OTg5MzMsInByb2ZpbGVJZCI6IjE5MjUyMWI0ZWZkYjQyNWM4OTMxZjAyYTg0OTZlMTFiIiwicHJvZmlsZU5hbWUiOiJTZXJpYWxpemFibGUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNiZGNkYzA5MTY0MThjZjgyZGNjNmQxYjkxNmNmZTgzZTU1ZTc0NzFlODA5NTMwZDNiYWM0NDZmMjk3N2UyYmQifX19;eyJ0aW1lc3RhbXAiOjE1NzI2NTU5MjY2MjEsInByb2ZpbGVJZCI6IjgyYzYwNmM1YzY1MjRiNzk4YjkxYTEyZDNhNjE2OTc3IiwicHJvZmlsZU5hbWUiOiJOb3ROb3RvcmlvdXNOZW1vIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTIwYTkwNmMzNzRkYmMyZWM0NTIzYzkwYTVjNGUwNjA0ZDA5YmZkZTlhN2VkYWQxMWE5M2NkMDhkZDk3YmFkIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NzI2NTU5MjY2MjEsInByb2ZpbGVJZCI6IjgyYzYwNmM1YzY1MjRiNzk4YjkxYTEyZDNhNjE2OTc3IiwicHJvZmlsZU5hbWUiOiJOb3ROb3RvcmlvdXNOZW1vIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTIwYTkwNmMzNzRkYmMyZWM0NTIzYzkwYTVjNGUwNjA0ZDA5YmZkZTlhN2VkYWQxMWE5M2NkMDhkZDk3YmFkIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NzI2NTU4NjQ2ODcsInByb2ZpbGVJZCI6IjIzZjFhNTlmNDY5YjQzZGRiZGI1MzdiZmVjMTA0NzFmIiwicHJvZmlsZU5hbWUiOiIyODA3Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83MjY5OTEwMTkzMGM4OWY2YzcxMmNjYjBjNjI4MDhhMzk5NzUyMDcxMDUwMzlmZTU4NzY2ZjJjODc2OGYyZDkxIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==;eyJ0aW1lc3RhbXAiOjE1NTU0NTM1MDg3OTksInByb2ZpbGVJZCI6ImU3NmYwZDlhZjc4MjQyYzM5NDY2ZDY3MjE3MzBmNDUzIiwicHJvZmlsZU5hbWUiOiJLbGxscmFoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTY0YzY2NGQ3M2ZmOTFmMjgzZjVhZTg1OGFjYTEzNGZjYmE3MzM5YmYyMmFmYWZlNWZlNDk4ODA4Mzc2NTFiIn19fQ==