itemName: '&7Beaver Mask'
lore:
- '&7A mask!'

potionType:
  - FAST_DIGGING;2
  - SPEED;1

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NTU0NDE0ODg4NzUsInByb2ZpbGVJZCI6IjJjMTA2NGZjZDkxNzQyODI4NGUzYmY3ZmFhN2UzZTFhIiwicHJvZmlsZU5hbWUiOiJOYWVtZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOThhZmQ2M2UzYzk4YjY3MWE5NGZhNWU5YjkzNjVmMjgyYjZhNDljM2EzY2QyN2YzMDcwZDAxOWVjZjBmNDM4ZCJ9fX0=