itemName: '&aDruggie Mask'
lore:
- '&7A mask!'

potionType:
  - POISON;1
  - SPEED;4

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NTU0NTMwNTkyMTUsInByb2ZpbGVJZCI6IjkxZjA0ZmU5MGYzNjQzYjU4ZjIwZTMzNzVmODZkMzllIiwicHJvZmlsZU5hbWUiOiJTdG9ybVN0b3JteSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjYwODgwMmU5YjlkMjU3MTY4YzQ1NGIzOWI3MmQzYzk2MWViZjNmMWUyNGRkYzVlMDczNjkwNmYxNGZjN2YwNyJ9fX0=