itemName: '&7Drunk Mask'
lore:
- '&7A mask!'

potionType:
  - NIGHT_VISION;2
  - INCREASE_DAMAGE;2
  - CONFUSION;1

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NTU0MzkzNjQ5NzQsInByb2ZpbGVJZCI6IjNmYzdmZGY5Mzk2MzRjNDE5MTE5OWJhM2Y3Y2MzZmVkIiwicHJvZmlsZU5hbWUiOiJZZWxlaGEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZmOTVjNjUxODRkODc2NjRhOTRlNjRkNTUyNmVjNGUxM2M3MGU5NTU0OTA3OWM3ZTI2MWVlOTI3NTcxZmE1MTMifX19