itemName: '&dRabbit Mask'
lore:
- '&7A mask!'

potionType:
  - JUMP;3
  - SPEED;1
  - HEAL;1

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NDY1MjU4NzIxNDgsInByb2ZpbGVJZCI6IjVjN2ZiNzhhMmQxMzQ5NTZhNWE1M2EyNGQ5NWY1YjRmIiwicHJvZmlsZU5hbWUiOiJQZWFyc29uSW5tYW4iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzExN2E4ZDUyN2Q3ZGI5YWI5NDk2Zjg2MDY0M2I3YmRiYmYyMDA1Y2YxZDY2MGQwYzllYTI0OGRhY2QwZjhjNjgiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==