itemName: '&4Warrior Mask'
lore:
- '&7A mask!'

potionType:
  - DAMAGE_RESISTANCE;1
  - INCREASE_DAMAGE;2

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1MTM4NDUyMTM0NTUsInByb2ZpbGVJZCI6ImIwZDczMmZlMDBmNzQwN2U5ZTdmNzQ2MzAxY2Q5OGNhIiwicHJvZmlsZU5hbWUiOiJPUHBscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjdhODY3MWQ2MWUzYWNhOGE3M2NkMmUzZDMyZGExMTFiODE1ZjM4YjZiN2Y5ZWJiODRhNDMyZmY4OGMzOTNkIn19fQ==