itemName: '&dWitch Mask'
lore:
- '&7A mask!'

potionType:
- REGENERATION;1
- INCREASE_DAMAGE;2

on-wear-commands:
- ''

texture:
  value: eyJ0aW1lc3RhbXAiOjE1NjQ5NDI4NTIxMzksInByb2ZpbGVJZCI6IjVkZTZlMTg0YWY4ZDQ5OGFiYmRlMDU1ZTUwNjUzMzE2IiwicHJvZmlsZU5hbWUiOiJBc3Nhc2luSmlhbmVyMjUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZjZWQ5OTJkOWY3YzRhNDg4MmIyNzFmNDBjMTkxOWM4ZTIzMTE3MzFkMDIxMGJlMDdlNTBhNjNhZDc3ZDA5MzUifX19