overworld_new_height: false
config_version: 1
debug_messages: false
expire_groups:
  default:
    permission: deathchestpro.expire.default
    teleport_cost: 0
    chest_block: CHEST
    unlock_after: -1
    time: 900
allow_break_chests: false
allow_killer_looting: true
drop_items_after_expire: false
lava_spawning: true
lava_protection: true
old_lava_protection: false
void_spawning_chest: true
auto_equip_armor: true
clickable_message: true
spawn_chest_on_highest_block: false
spawn_chest_on_pvp_kill: true
start_timer_at_death: false
store_experience: true
store_experience_percent: 75.0
max_player_chests: 3
teleport_cooldown: 16
deathchest_fireworks:
  enabled: true
  interval: 32
disabled_worlds:
- example_world
disabled_regions:
- example_region
sounds:
  click: UI_BUTTON_CLICK
  gui_open: ENTITY_EXPERIENCE_ORB_PICKUP
hologram:
  enabled: true
  death_date_format: hh:mm
  lines:
  - '&a&lOwner: &6&l%player%'
  - '&f&l%item_count% Items &2&l/ %xp% XP'
  - '&b&l%timeleft% left'
  - Time of Death %death_date%
deathchest_inv_title: '&7%player%''s DeathChest'
placeholders_format:
  location: '%x%, %y%, %z%, %world%'
blacklisted_blocks:
- portal
- bed
- sign
