menu_title: '&3> &bCustom Recepies'
open_command:
  - help
open_commands:
  - '[message]&#1b83e7&lO&#009bf1&lr&#00b0f4&lb&#00c4f2&li&#1bd7ee&ls &#9F9890&l>> &#1be7cb&lO&#00e9c4&lp&#00eabc&le&#00ebb3&ln&#00eca9&li&#00ed9e&ln&#1bee92&lg
 &bCustom Recepies Menu!'
size: 35
# as always, only cool people can open this menu :)
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: everyone
      deny_commands:
        - "[message] &8[&bDeluxe&eMenus&8] &cYou don't have perms for this!"
items:
  'Big Dreapleaf':
    material: BIG_DRIPLEAF
    slot: 10
    priority: 1
    update: true
    hide_attributes:  true
    display_name: '&fBig Dripleaf'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] big_dreaplead_menu'
      - '[close]'
  'AZELA':
    material: AZALEA
    slot: 11
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fAzela'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] azela_menu'
      - '[close]'
  'FLOWERINGAZELA':
    material: FLOWERING_AZALEA
    slot: 12
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fFlowering_Azela'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] flowering_azalea_menu'
      - '[close]'
  'Go back': 
    material: BARRIER
    slot: 31
    priority: 1
    update: true
    hide_attributes:  true
    display_name: '&c&lExit Back'
    lore:
      - '&7This will take you back to the &bHelp Menu.'
      - '&7'
      - '&#76aff2&lL&#77b0ef&le&#78b0eb&lf&#79b1e8&lt &#7bb1e4&lc&#7cb1e1&ll&#7fb2dd&li&#81b2da&lc&#84b2d6&lk &#86b2d3&lt&#89b2cf&lo &#8cb2cc&lp&#8fb2c9&lr&#93b2c5&lo&#96b1c2&lc&#99b1bf&le&#9db1bc&le&#a0b0b9&ld&#a4b0b6&l!'
    left_click_commands:
      - '[openguimenu] help_menu'
      - '[close]'
  'SPORE_BLOSSOM':
    material: SPORE_BLOSSOM
    slot: 13
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fSpore Blossom'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] spore_blossom_menu'
      - '[close]'
  'MOSS_BLOCK':
    material: MOSS_BLOCK
    slot: 14
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fMoss Block'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] moss_block_menu'
      - '[close]'
  'bell':
    material: BELL
    slot: 16
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fBell'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] bell_menu'
      - '[close]'
  'small dripleaf':
    material: SMALL_DRIPLEAF
    slot: 15
    priority: 1
    update: true
    hide_attributes: true
    display_name: '&fSmall Dripleaf'
    lore:
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] small_dripleaf_menu'
      - '[close]'
  'Custom Craft': 
    material: GUNPOWDER
    slot: 20
    priority: 1
    hide_attributes: true
    display_name: '&b&lGunpowder'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] gunpowder_menu'
      - '[close]'
  'Inksac': 
    material: INK_SAC
    slot: 21
    priority: 1
    hide_attributes: true
    display_name: '&b&lInk Sac'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] inksac_menu'
      - '[close]'  
  'Magazine': 
    material: GHAST_TEAR
    slot: 22
    nbt_int: 'CustomModelData:1'
    priority: 1
    hide_attributes: true
    display_name: '&b&lMagazine'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] magazine_menu'
      - '[close]'
  'Light': 
    material: GHAST_TEAR
    slot: 23
    nbt_int: 'CustomModelData:2'
    priority: 1
    hide_attributes: true
    display_name: '&b&lClip'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] clip_menu'
      - '[close]'
  'Shell': 
    material: GHAST_TEAR
    slot: 24
    nbt_int: 'CustomModelData:3'
    priority: 1
    hide_attributes: true
    display_name: '&b&lShotgun Shell'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] shotgun_menu'
      - '[close]'
  'BIg SHULKER': 
    material: SHULKER_BOX
    slot: 19
    priority: 1
    hide_attributes: true
    display_name: '&b&lBig Shulker'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] big_shulker_menu'
      - '[close]' 
  'Rocket': 
    material: GHAST_TEAR
    slot: 25
    priority: 1
    nbt_int: 'CustomModelData:510'
    hide_attributes: true
    display_name: '&b&lRocket'
    lore:
      - '&7Find the Custom Recepie here!'
      - '&7'
      - '&b&lLeft&7 Click to Continue'
    left_click_commands:
      - '[openguimenu] rocket_menu'
      - '[close]'   
  'placeholder':
    material: BLACK_STAINED_GLASS_PANE
    slots: 
      - 0-8
      - 9
      - 13-17
      - 18
      - 22
      - 24
      - 26
      - 27-31
      - 31-35
    priority: 2
    display_name: ยง      

