#  A DeluxeMenus advanced configuration guide
#=========================================================
menu_title: '&3> &b&lTowny Help'
open_command:
  - towny command help
open_commands:
  - '[message]&#1b83e7&lO&#009bf1&lr&#00b0f4&lb&#00c4f2&li&#1bd7ee&ls &#9F9890&l>> &#1be7cb&lO&#00e9c4&lp&#00eabc&le&#00ebb3&ln&#00eca9&li&#00ed9e&ln&#1bee92&lg
 &bTowny Menu!'
size: 27
# as always, only cool people can open this menu :)
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: everyone
      deny_commands:
        - "[message] &8[&bDeluxe&eMenus&8] &cYou don't have perms for this!"
items:
  'Town Help':
    material: hdb-45670
    slot: 12
    priority: 1
    update: true
    hide_attributes:  true
    display_name: '&b&LTown Help'
    lore:
      - '&7This will take you to nation help.'
      - '&r'
      - '&#55ffff&lL&#61fcfb&le&#6cf8f8&lf&#75f5f4&lt &#7df1f1&lc&#84eeed&ll&#8beaea&li&#91e7e6&lc&#97e3e3&lk &#9ce0df&lt&#a1dcdc&lo &#a6d9d8&lc&#aad5d5&lo&#aed2d1&ln&#b2cece&lt&#b6cbca&li&#bac7c7&ln&#bdc4c3&lu&#c0c0c0&le!'
    left_click_commands:
      - '[openguimenu] town_menu'
      - '[close]'
  'Nation Help':
    material: hdb-37753

    slot: 14
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&LNation Help'
    lore:
      - '&7This will take you to nation help.'
      - '&r'
      - '&#55ffff&lL&#61fcfb&le&#6cf8f8&lf&#75f5f4&lt &#7df1f1&lc&#84eeed&ll&#8beaea&li&#91e7e6&lc&#97e3e3&lk &#9ce0df&lt&#a1dcdc&lo &#a6d9d8&lc&#aad5d5&lo&#aed2d1&ln&#b2cece&lt&#b6cbca&li&#bac7c7&ln&#bdc4c3&lu&#c0c0c0&le!'
    left_click_commands:
      - '[openguimenu] nation_menu'
      - '[close]'
  'Go back': 
    material: BARRIER
    slot: 22
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lExit Back'
    lore:
      - '&7This will take you back to the &bHelp Menu.'
      - '&7'
      - '&#76aff2&lL&#77b0ef&le&#78b0eb&lf&#79b1e8&lt &#7bb1e4&lc&#7cb1e1&ll&#7fb2dd&li&#81b2da&lc&#84b2d6&lk &#86b2d3&lt&#89b2cf&lo &#8cb2cc&lp&#8fb2c9&lr&#93b2c5&lo&#96b1c2&lc&#99b1bf&le&#9db1bc&le&#a0b0b9&ld&#a4b0b6&l!'
    left_click_commands:
      - '[openguimenu] Help_menu'
      - '[close]'
  'YOUTUBE LINK': 
    material: hdb-35517
    slot: 13
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&a&lFind out more about Towny!'
    lore:
      - '&7This will show you more stuff about towny!'
      - '&7'
      - '&#55ffff&lL&#61fcfb&le&#6cf8f8&lf&#75f5f4&lt &#7df1f1&lc&#84eeed&ll&#8beaea&li&#91e7e6&lc&#97e3e3&lk &#9ce0df&lt&#a1dcdc&lo &#a6d9d8&lc&#aad5d5&lo&#aed2d1&ln&#b2cece&lt&#b6cbca&li&#bac7c7&ln&#bdc4c3&lu&#c0c0c0&le!'
    left_click_commands:
      - '[message] &7Follow this link to find out more about towny &chttps://youtu.be/2BfaFGGjgIQ'
      - '[close]'

      


