menu_title: '&3> &b&lTown Help'
open_command:
  - town command help
open_commands:
  - '[message]&#1b83e7&lO&#009bf1&lr&#00b0f4&lb&#00c4f2&li&#1bd7ee&ls &#9F9890&l>> &#1be7cb&lO&#00e9c4&lp&#00eabc&le&#00ebb3&ln&#00eca9&li&#00ed9e&ln&#1bee92&lg
 &bTownMenu!'
size: 27
# as always, only cool people can open this menu :)
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: everyone
      deny_commands:
        - "[message] &8[&bDeluxe&eMenus&8] &cYou don't have perms for this!"
items:
  'How to make a town':
    material: hdb-45670
    slot: 10
    priority: 1
    update: true
    hide_attributes:  true
    display_name: '&b&LHow to make a town.'
    lore:
      - '&7To create a town do &b&l/t new (town name).'
      - '&7This action will take &b&l$2500' 
      - '&7away from your &c&lpersonal&r&7 Balance.'
      - '&7To check your balance do &b&l/bal.'
  'How to claim land':
    material: GRASS_BLOCK

    slot: 11
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&LHow to claim land.'
    lore:
      - '&7To claim more land for your town do &b&l/t claim&r&7.'
      - '&7This will cost your town &b&l$250&r&7.'
      - '&7To check how much money is in your town simply do &b&l/t&r&7.'
      - '&c&lYou can claim more land by having'
      - '&c&Lmore people in your town.'
  'Ranks': 
    material: GOLD_INGOT
    
    slot: 12
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lGiving ranks to players'
    lore:
       - '&7To give players ranks do'
       - '&b&L/t rank add (playername) (rank).'
       - '&c&lOnly Mayors and Co-Mayors&r&7' 
       - '&7can preform this command.'
  'T spawn': 
    material: ENDER_CHEST
    slot: 14
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lSetting T spawn'
    lore:
       - '&7Mayors and Co-Mayors' 
       - '&7`can set the town spawn by doing.'
       - '&b&l/t set spawn.'
  'Bonus Claims': 
    material: hdb-6300
    slot: 13
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lClaiming Bonus Plots'
    lore:
       - '&7To claim bonus plots simply do .'
       - '&b&l/t buy bonus (number of plots).'
       - '&7The price will increase the more you buy.'
  'Town Menu': 
    material: COMMAND_BLOCK
    slot: 16
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lTown Menu'
    lore:
       - '&7To simply edit your town with townmenu.'
       - '&7To open this up do.'
       - '&b&l/townmenu).'  
  'Inviting people to your town': 
    material: hdb-18213
    slot: 15
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lHow to invite people to your town.'
    lore:
       - '&7To invite someone to your town do'
       - '&b&l/t add (playername).'
  'Go back': 
    material: BARRIER
    slot: 22
    priority: 2
    update: true
    hide_attributes:  true
    display_name: '&b&lExit Back'
    lore:
      - '&7This will take you back to the &bTowny Menu.'
      - '&7'
      - '&#76aff2&lL&#77b0ef&le&#78b0eb&lf&#79b1e8&lt &#7bb1e4&lc&#7cb1e1&ll&#7fb2dd&li&#81b2da&lc&#84b2d6&lk &#86b2d3&lt&#89b2cf&lo &#8cb2cc&lp&#8fb2c9&lr&#93b2c5&lo&#96b1c2&lc&#99b1bf&le&#9db1bc&le&#a0b0b9&ld&#a4b0b6&l!'
    left_click_commands:
      - '[openguimenu] towny_menu'
      - '[close]'
 
   